services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nautik
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nautik
      MYSQL_USER: nautik
      MYSQL_PASSWORD: nautik
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config-all/db/nautik_260129.sql:/docker-entrypoint-initdb.d/nautik.sql:ro
    ports:
      - "3306:3306"
    networks:
      - nautikNet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_nautik
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - nautikNet
  vue-dev:
    container_name: vue-dev
    image: node:22
    stdin_open: true
    tty: true
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8082:5173"
    volumes:
      - "./public/vue:/app"
    networks:
      - nautikNet

  quasar:
    container_name: quasar-dev
    image: node:22
    stdin_open: true
    tty: true
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8083:5173"
    volumes:
      - "./admin/:/app"
    networks:
      - nautikNet


  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    container_name: laravel_app
    volumes:
      - ./api-laravel/laravel:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - nautikNet

  laravel-web:
    image: httpd:2.4
    container_name: apache_web
    ports:
      - "8085:80"
    volumes:
      - ./api-laravel/laravel:/var/www/html
      - vendor:/var/www/html/vendor
      - ./config-all/apache/000-default.conf:/usr/local/apache2/conf/extra/000-default.conf
    depends_on:
      - laravel-app
    command: >
      sh -c "
      sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf &&
      sed -i '/LoadModule proxy_module/s/^#//g' /usr/local/apache2/conf/httpd.conf &&
      sed -i '/LoadModule proxy_fcgi_module/s/^#//g' /usr/local/apache2/conf/httpd.conf &&
      echo 'Include conf/extra/000-default.conf' >> /usr/local/apache2/conf/httpd.conf &&
      httpd-foreground
      "
    

    networks:
      - nautikNet
  backend:
    build:
      context: .
      dockerfile: Dockerfile-spring
    container_name: springboot_app
    expose:
      - "8080"
    networks:
      - nautikNet

  apache:
    image: httpd:2.4
    container_name: apache_spring
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./config-all/apache/apache.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - backend
    networks:
      - nautikNet


networks:
  nautikNet:
    driver: bridge

volumes:
  node_modules:
  mysql_data:
  vendor: