ServerRoot "/usr/local/apache2"
ServerName localhost

# ---- MPM ----
LoadModule mpm_event_module modules/mod_mpm_event.so

# ---- Core / Auth ----
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so

# ---- Proxy ----
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# ---- Básicos ----
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so

Listen 80

PidFile logs/httpd.pid

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

<VirtualHost *:80>

    ProxyPreserveHost On
    ProxyRequests Off

    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass / http://backend:8080/
    ProxyPassReverse / http://backend:8080/

</VirtualHost>
